abstract class ShowStudentsScoreStates{}

class ShowStudentsScoreInitState extends ShowStudentsScoreStates{}

class GetAllStudentsScoreLoadingState extends ShowStudentsScoreStates{}
class GetAllStudentsScoreSuccessState extends ShowStudentsScoreStates{}
class GetAllStudentsScoreErrorState extends ShowStudentsScoreStates{}